services:
  - name: karib-hair
    type: web
    plan: free
    env: ruby
    buildCommand: bin/render-build.sh
    startCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgre-db
          property: connectionString
      - key: MAPBOX_API_KEY
        sync: false

databases:
  - name: postgre-db
    plan: free
    ipAllowList: []
